### PR TITLE
Record more fields into the NMC status

### LINKED ISSUE #783: Cherry-picking error for `d2fbdcb28777c352b52e9c2a704ba40a57c33b2b`
gitstream tried to cherry-pick commit `d2fbdcb28777c352b52e9c2a704ba40a57c33b2b` from `https://github.com/kubernetes-sigs/kernel-module-management` but was unable to do so.

Commit message:
```
Record more fields into the NMC status (#573)

Record the service account name as well as the imageRepoSecret used in a
successful loader Pod into the NMC status.
The service account name is stored as part of the PodSpec.
For the imageRepoSecret name, add that volume under a well-known name
that can be looked up by SyncStatus().
```

Please cherry-pick the commit manually.

---

**Error**:
```
could not cherry-pick: error running git: exit status 1
```
---

**Command**: `/usr/bin/git cherry-pick -n d2fbdcb28777c352b52e9c2a704ba40a57c33b2b -m1`

<details><summary>Output</summary>

```
Auto-merging internal/controllers/nmc_reconciler.go
CONFLICT (content): Merge conflict in internal/controllers/nmc_reconciler.go
Auto-merging internal/controllers/nmc_reconciler_test.go
error: could not apply d2fbdcb2... Record more fields into the NMC status (#573)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'

```

</details>

---

Upstream-Commit: d2fbdcb28777c352b52e9c2a704ba40a57c33b2b

### PR DESCRIPTION
**Pull request by qbarrand**
Record the service account name as well as the imageRepoSecret used in a successful loader Pod into the NMC status.
The service account name is stored as part of the PodSpec. For the imageRepoSecret name, add that volume under a well-known name that can be looked up by `SyncStatus()`.

Fixes #783

/cc @yevgeny-shnaidman

### CODE REVIEW

File: internal/controllers/nmc_reconciler.go [hunk 1]
```diff
@@ -578,6 +590,8 @@ func (p *podManagerImpl) CreateLoaderPod(ctx context.Context, nmc client.Object,
 		}
 	}
 
+	labels.SetLabel(pod, actionLabelKey, WorkerActionLoad)
```
Comment (yevgeny-shnaidman) [inline internal/controllers/nmc_reconciler.go:593]: actionLabelKey is already set in line 586

Comment (qbarrand) [reply internal/controllers/nmc_reconciler.go:592]: Fixed, thanks!
