### PR TITLE
Publish build & sign events

### LINKED ISSUE #793: Cherry-picking error for `b909f193879aa52c962ed0375f6050a417ecfc8d`
gitstream tried to cherry-pick commit `b909f193879aa52c962ed0375f6050a417ecfc8d` from `https://github.com/kubernetes-sigs/kernel-module-management` but was unable to do so.

Commit message:
```
Publish build & sign events (#577)

Add a new reconciler to watch build & signing Pods.
```

Please cherry-pick the commit manually.

---

**Error**:
```
could not cherry-pick: error running git: exit status 1
```
---

**Command**: `/usr/bin/git cherry-pick -n b909f193879aa52c962ed0375f6050a417ecfc8d -m1`

<details><summary>Output</summary>

```
Auto-merging cmd/manager-hub/main.go
CONFLICT (content): Merge conflict in cmd/manager-hub/main.go
Auto-merging cmd/manager/main.go
Auto-merging config/rbac-base/kustomization.yaml
Auto-merging go.mod
CONFLICT (content): Merge conflict in go.mod
CONFLICT (modify/delete): internal/build/pod/maker.go deleted in HEAD and modified in b909f193 (Publish build & sign events (#577)).  Version b909f193 (Publish build & sign events (#577)) of internal/build/pod/maker.go left in tree.
CONFLICT (modify/delete): internal/build/pod/maker_test.go deleted in HEAD and modified in b909f193 (Publish build & sign events (#577)).  Version b909f193 (Publish build & sign events (#577)) of internal/build/pod/maker_test.go left in tree.
Auto-merging internal/constants/constants.go
Auto-merging internal/controllers/module_nmc_reconciler.go
CONFLICT (content): Merge conflict in internal/controllers/module_nmc_reconciler.go
Auto-merging internal/controllers/nmc_reconciler.go
CONFLICT (content): Merge conflict in internal/controllers/nmc_reconciler.go
Auto-merging internal/filter/filter_test.go
CONFLICT (content): Merge conflict in internal/filter/filter_test.go
CONFLICT (modify/delete): internal/sign/pod/signer.go deleted in HEAD and modified in b909f193 (Publish build & sign events (#577)).  Version b909f193 (Publish build & sign events (#577)) of internal/sign/pod/signer.go left in tree.
CONFLICT (modify/delete): internal/sign/pod/signer_test.go deleted in HEAD and modified in b909f193 (Publish build & sign events (#577)).  Version b909f193 (Publish build & sign events (#577)) of internal/sign/pod/signer_test.go left in tree.
error: could not apply b909f193... Publish build & sign events (#577)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'

```

</details>

---

Upstream-Commit: b909f193879aa52c962ed0375f6050a417ecfc8d

### PR DESCRIPTION
**Pull request by qbarrand**
Add a new reconciler to watch build & signing Build objects.

Addresses [MGMT-15286](https://issues.redhat.com//browse/MGMT-15286)
Addresses [MGMT-15287](https://issues.redhat.com//browse/MGMT-15287)

Fixes #793

/cc @yevgeny-shnaidman

### CODE REVIEW

File: internal/controllers/job_event_reconciler.go [hunk 1]
```diff
@@ -0,0 +1,223 @@
...
+	}
+
+	je := &jobEvent{
+		jobType: titler.String(jobType),
+	}
+
+	return je, nil
+}
+
+type JobEventReconciler struct {
```
Comment (yevgeny-shnaidman) [inline internal/controllers/job_event_reconciler.go:74]: WDYT about renaming this file to build_event_reconciler? And renaming all the internal variables/functions accordingly? I think it is more appropriate for downstream

Comment (qbarrand) [reply internal/controllers/job_event_reconciler.go:74]: I was wondering about this, and I think it may make cherry-picks slightly more difficult. I called the type `JobEventReconciler` so that it works for both upstream and downstream.

Comment (yevgeny-shnaidman) [reply internal/controllers/job_event_reconciler.go:74]: I was thinking about renaming it to build_sign_events_reconciler (which will be compatible to both upstream and downstream.  You will still need to manually cherry-pick , since the watch is different anyway

Comment (qbarrand) [reply internal/controllers/job_event_reconciler.go]: This PR now includes https://github.com/kubernetes-sigs/kernel-module-management/pull/589 as well. PTAL.

File: internal/controllers/build_sign_events_reconciler.go [hunk 2]
```diff
@@ -0,0 +1,223 @@
...
+	"sigs.k8s.io/controller-runtime/pkg/reconcile"
+)
+
+const (
+	BuildSignEventsReconcilerName = "BuildSignEvents"
+
+	createdAnnotationKey = "kmm.node.kubernetes.io/created-event-sent"
+)
+
+type jobEvent struct {
```
Comment (yevgeny-shnaidman) [inline internal/controllers/build_sign_events_reconciler.go:36]: I think all those JobEvent should be rename with buildSignEvents. WDYT?

Comment (qbarrand) [reply internal/controllers/build_sign_events_reconciler.go:36]: I would leave it like this - IMO no need to make it less generic.

Comment (yevgeny-shnaidman) [reply internal/controllers/build_sign_events_reconciler.go:36]: But we are not talking about job event, we are talking about BuildSign event.  job is just an implementation for upstream, no?

Comment (qbarrand) [reply internal/controllers/build_sign_events_reconciler.go:36]: Build and Sign are both types of jobs. That is why the initial reconciler was called job - to accomodate any workload that the controller may create to produce images.
Renaming this type to `buildOrSignEvent` feels awkward imho.
