### PR TITLE
Use OpenShift builds for signing

### LINKED ISSUE #461: Cherry-picking error for `4ea7960e4bdd8f5767a5036ba151c96c21d46fd6`
gitstream tried to cherry-pick commit `4ea7960e4bdd8f5767a5036ba151c96c21d46fd6` from `https://github.com/kubernetes-sigs/kernel-module-management` but was unable to do so.

Commit message:
```
Use kaniko for signing (#313)

Replace the custom implementation with a kaniko-based setup where we
generate the Dockerfile dynamically from a template.
Use some functions from the build package.
Remove methods from the registry package that are now unused.
```

Please cherry-pick the commit manually.

---

**Error**:
```
could not cherry-pick: error running git: exit status 1
```
---

**Command**: `/usr/bin/git cherry-pick -n 4ea7960e4bdd8f5767a5036ba151c96c21d46fd6 -m1`

<details><summary>Output</summary>

```
Auto-merging Dockerfile.signimage
CONFLICT (content): Merge conflict in Dockerfile.signimage
Auto-merging Makefile
CONFLICT (content): Merge conflict in Makefile
Auto-merging cmd/manager-hub/main.go
CONFLICT (content): Merge conflict in cmd/manager-hub/main.go
Auto-merging cmd/manager/main.go
CONFLICT (content): Merge conflict in cmd/manager/main.go
CONFLICT (modify/delete): cmd/signimage/signimage.go deleted in 4ea7960 (Use kaniko for signing (#313)) and modified in HEAD.  Version HEAD of cmd/signimage/signimage.go left in tree.
Auto-merging internal/registry/mock_registry_api.go
CONFLICT (content): Merge conflict in internal/registry/mock_registry_api.go
Auto-merging internal/registry/registry.go
CONFLICT (content): Merge conflict in internal/registry/registry.go
Auto-merging internal/sign/job/manager_test.go
Auto-merging internal/sign/job/signer.go
CONFLICT (content): Merge conflict in internal/sign/job/signer.go
Auto-merging internal/sign/job/signer_test.go
CONFLICT (content): Merge conflict in internal/sign/job/signer_test.go
Auto-merging internal/sign/suite_test.go
Auto-merging internal/utils/volumehelper_test.go
error: could not apply 4ea7960... Use kaniko for signing (#313)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'

```

</details>

---

Upstream-Commit: 4ea7960e4bdd8f5767a5036ba151c96c21d46fd6

### PR DESCRIPTION
**Pull request by qbarrand**
Replace the custom implementation with a Build-based setup where we generate the Dockerfile dynamically from a template. Use some functions from the build package.
Remove methods from the registry package that are now unused.

Fixes #461

### CODE REVIEW

File: cmd/manager-hub/main.go [hunk 1]
```diff
@@ -22,6 +22,9 @@ import (
 
 	buildv1 "github.com/openshift/api/build/v1"
 	imagev1 "github.com/openshift/api/image/v1"
+	buildocpbuild "github.com/rh-ecosystem-edge/kernel-module-management/internal/build/ocpbuild"
+	signocpbuild "github.com/rh-ecosystem-edge/kernel-module-management/internal/sign/ocpbuild"
```
Comment (ybettan) [inline cmd/manager-hub/main.go:26]: How about we just call them `build` and `sign` in the alias? `buildocpbuild` and `signocpbuild` are a bit confusing.

File: controllers/module_reconciler.go [hunk 2]
```diff
@@ -115,12 +112,6 @@ func (r *ModuleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 		return res, fmt.Errorf("failed to get the requested %s KMMO CR: %w", req.NamespacedName, err)
 	}
 
-	if req.Namespace != r.operatorNamespace {
-		if err = r.caHelper.Sync(ctx, req.Namespace, mod); err != nil {
-			return ctrl.Result{}, fmt.Errorf("failed to synchronize CA ConfigMaps: %v", err)
-		}
-	}
```
Comment (ybettan) [inline controllers/module_reconciler.go:122]: Why are we removing it?

File: controllers/module_reconciler.go [hunk 3]
```diff
@@ -25,14 +25,14 @@ import (
...
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/build"
-	"github.com/rh-ecosystem-edge/kernel-module-management/internal/ca"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/daemonset"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/filter"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/metrics"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/module"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/sign"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/statusupdater"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/utils"
+	build2 "github.com/rh-ecosystem-edge/kernel-module-management/internal/utils/build"
```
Comment (ybettan) [inline controllers/module_reconciler.go:35]: Why is this called `build2`?

File: internal/build/ocpbuild/maker.go [hunk 4]
```diff
@@ -119,17 +124,17 @@ func (m *maker) MakeBuildTemplate(
 		Type:       buildv1.BuildSourceDockerfile,
 	}
 
-	sourceConfigHash, err := hashstructure.Hash(sourceConfig, nil)
+	sourceConfigHash, err := hashstructure.Hash(sourceConfig, hashstructure.FormatV2, nil)
```
Comment (ybettan) [inline internal/build/ocpbuild/maker.go:127]: Wondering how this is working? `hashstrucutre` was renamed to `v2`...

File: internal/cluster/cluster.go [hunk 5]
```diff
@@ -6,6 +6,7 @@ import (
 	"fmt"
 	"strings"
 
+	build2 "github.com/rh-ecosystem-edge/kernel-module-management/internal/utils/build"
```
Comment (ybettan) [inline internal/cluster/cluster.go:9]: Why is this named `build2`? Why not just using `build`?

File: internal/preflight/preflight.go [hunk 6]
```diff
@@ -13,6 +13,7 @@ import (
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/sign"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/statusupdater"
 	"github.com/rh-ecosystem-edge/kernel-module-management/internal/utils"
+	build2 "github.com/rh-ecosystem-edge/kernel-module-management/internal/utils/build"
```
Comment (ybettan) [inline internal/preflight/preflight.go:16]: Same question

File: internal/sign/ocpbuild/maker.go [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+	v1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/types"
+	"k8s.io/utils/pointer"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
+)
+
+type TemplateData struct {
```
Comment (ybettan) [inline internal/sign/ocpbuild/maker.go:24]: I don't see anyone outside this package using `TempalteData`. Any reason it is exported?

File: controllers/module_reconciler.go (hunk 2 above)
Comment (qbarrand) [reply controllers/module_reconciler.go:122]: This helper was providing the CA certs to signing Jobs. We don't need it anymore because we use Builds, which mount the CA certs automatically.

File: internal/sign/ocpbuild/maker.go [hunk 8]
```diff
@@ -0,0 +1,255 @@
...
+								},
+							},
+						},
+					},
+				},
+				Output:         buildTarget,
+				NodeSelector:   mld.Selector,
+				MountTrustedCA: pointer.Bool(true),
+			},
+		},
```
Comment (ybettan) [inline internal/sign/ocpbuild/maker.go:209]:
```suggestion
		Spec: spec,
```

File: internal/build/ocpbuild/maker.go (hunk 4 above)
Comment (qbarrand) [reply internal/build/ocpbuild/maker.go:127]: This is the expected behaviour when the version is the last element in the import path.

File: controllers/module_reconciler.go (hunk 3 above)
Comment (qbarrand) [reply controllers/module_reconciler.go]: Fixed, thanks!

File: internal/cluster/cluster.go (hunk 5 above)
Comment (qbarrand) [reply internal/cluster/cluster.go]: Fixed, thanks!

File: internal/preflight/preflight.go (hunk 6 above)
Comment (qbarrand) [reply internal/preflight/preflight.go]: Fixed, thanks!

File: internal/sign/ocpbuild/maker.go (hunk 8 above)
Comment (qbarrand) [reply internal/sign/ocpbuild/maker.go]: Wow, not sure how I missed this duplication. Thanks!

File: internal/sign/ocpbuild/manager.go [hunk 9]
```diff
@@ -0,0 +1,122 @@
...
+	return &manager{
+		client:          client,
+		maker:           maker,
+		ocpBuildsHelper: ocpBuildsHelper,
+		authFactory:     authFactory,
+		registry:        registry,
+	}
+}
+
+func (bcm *manager) GarbageCollect(ctx context.Context, modName, namespace string, owner metav1.Object) ([]string, error) {
```
Comment (ybettan) [inline internal/sign/ocpbuild/manager.go:45]:
```suggestion
func (m *manager) GarbageCollect(ctx context.Context, modName, namespace string, owner metav1.Object) ([]string, error) {
```

File: internal/sign/ocpbuild/manager.go [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+
+	exists, err := module.ImageExists(ctx, bcm.authFactory, bcm.registry, mld, mld.ContainerImage)
+	if err != nil {
+		return false, fmt.Errorf("failed to check existence of image %s: %w", mld.ContainerImage, err)
+	}
+
+	return !exists, nil
+}
+
+func (bcm *manager) Sync(
```
Comment (ybettan) [inline internal/sign/ocpbuild/manager.go:65]:
```suggestion
func (m *manager) Sync(
```

File: internal/sign/ocpbuild/manager.go [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+		ocpBuildsHelper: ocpBuildsHelper,
+		authFactory:     authFactory,
+		registry:        registry,
+	}
+}
+
+func (bcm *manager) GarbageCollect(ctx context.Context, modName, namespace string, owner metav1.Object) ([]string, error) {
+
+	//Garbage Collection noti (yet) implemented for Build
+	return nil, nil
```
Comment (ybettan) [inline internal/sign/ocpbuild/manager.go:48]: @yevgeny-shnaidman As we didn't open any issue for sign jobs not being collected u/s from the hub version.
Would you mind making sure this current implementation is working with the u/s fix that you plan?

File: internal/utils/build/utils.go [hunk 12]
```diff
@@ -0,0 +1,36 @@
...
+	"fmt"
+
+	buildv1 "github.com/openshift/api/build/v1"
+	"github.com/rh-ecosystem-edge/kernel-module-management/internal/api"
+	"github.com/rh-ecosystem-edge/kernel-module-management/internal/constants"
+)
+
+const (
+	HashAnnotation = "kmm.node.kubernetes.io/last-hash"
+
```
Comment (ybettan) [inline internal/utils/build/utils.go:13]:
```suggestion
```

Comment (qbarrand) [reply internal/utils/build/utils.go:13]: The new line is here to separate the exported constant from the unexported one.

**Comment by yevgeny-shnaidman** [comment]
sign/manager.go and build/manager.go are becoming practically the same ( except for some very minor differences). WDYT about unifying them? The same goes for the upstream. Maybe not in this PR, but it will save us code and we can move the utils/build under the unified directory

**Comment by qbarrand** [comment]
@yevgeny-shnaidman
> sign/manager.go and build/manager.go are becoming practically the same ( except for some very minor differences). WDYT about unifying them?

This is the purpose of https://github.com/kubernetes-sigs/kernel-module-management/pull/364 (upstream), the big refactor that unifies Job / Build management.
